
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dishyma
 * @author rdzAndresito
 * @author gorda
 */
public class SignoZodiaco extends javax.swing.JFrame {

    /**
     * Creates new form SignoZodiaco
     */
    public SignoZodiaco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textMes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        textDia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setText("Dia");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("Mes");

        textFinal.setEnabled(false);
        textFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFinalActionPerformed(evt);
            }
        });

        jLabel4.setText("Tu signo es:");

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textDia, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(textMes, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton3)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainMenu newframe = new MainMenu();
        newframe.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int diaN = Integer.parseInt(textDia.getText()); //convierte la cadena a enteros.
        int mesN = Integer.parseInt(textMes.getText()); //convierte la cadena a enteros.

        if (diaN > 31 || diaN < 1) {
            System.out.println("Te saliste del rango, eres un malnacido :( ");
        } else if (mesN > 12 || mesN < 1) {
            System.out.println("Te saliste del rango");
        } else {
            switch (mesN) {
                case (1) -> {
                    if (diaN >= 1 && diaN <= 20) {
                        
                        textFinal.setText("Capricornio.");
                        
                        /*System.out.println("_______________________");
                        System.out.println("| Tu eres Capricornio |");
                        System.out.println("|_____________________|");*/
                    } else if (diaN >= 21 && diaN <= 31) {
                        
                        textFinal.setText("Acuario.");
                        
                        /*System.out.println("_______________________");
                        System.out.println("| Tu signo es Acuario |");
                        System.out.println("|_____________________|");*/
                    }
                }
                case (2) -> {
                    if (diaN >= 1 && diaN <= 19) {
                        
                        textFinal.setText("Acuario.");
                        
                        /*System.out.println("___________________");
                        System.out.println("| Tu eres Acuario |");
                        System.out.println("|_________________|");*/

                    } else if (diaN >= 20 && diaN <= 29) {
                        
                        textFinal.setText("Piscis.");
                        
                        /*System.out.println("__________________");
                        System.out.println("| Tu eres piscis |");
                        System.out.println("|________________|");*/

                    } else {
                        
                        textFinal.setText("ERROR.");
                        JOptionPane.showMessageDialog(null, "Eres un Dios naciste un dia que no existe!");
                        
                        /*System.out.println("______________________________________________");
                        System.out.println("| Eres un Dios naciste un dia que no existe! |");
                        System.out.println("|____________________________________________|");*/
                    }
                }
                case (3) -> {
                    if (diaN >= 1 && diaN <= 20) {
                        
                        textFinal.setText("Piscis.");
                        
                        /*System.out.println("_________________");
                        System.out.println("| Tu eres Piscis |");
                        System.out.println("|________________|");*/
                    } else if (diaN >= 21 && diaN <= 31) {
                        
                        textFinal.setText("Aries.");
                        
                        /*System.out.println("_________________");
                        System.out.println("| Tu eres Aries |");
                        System.out.println("|_______________|");*/
                    }
                }
                case (4) -> {
                    if (diaN >= 1 && diaN <= 20) {
                        
                        textFinal.setText("Aries.");
                        
                        /*System.out.println("_________________");
                        System.out.println("| Tu eres Aries |");
                        System.out.println("|_______________|");*/
                    } else if (diaN >= 21 && diaN <= 30) {
                        
                        textFinal.setText("Tauro.");
                        
                        /*System.out.println("_________________");
                        System.out.println("| Tu eres Tauro |");
                        System.out.println("|_______________|");*/
                    } else {
                        
                        
                        textFinal.setText("ERROR.");
                        JOptionPane.showMessageDialog(null, "Eres un Dios naciste un dia que no existe!");
                        
                        /*System.out.println("______________________________________________");
                        System.out.println("| Eres un Dios naciste un dia que no existe! |");
                        System.out.println("|____________________________________________|");*/
                    }
                }
                case (5) -> {
                    if (diaN >= 1 && diaN <= 21) {
                        
                        textFinal.setText("Tauro.");
                        
                        /*System.out.println("_________________");
                        System.out.println("| Tu eres Tauro |");
                        System.out.println("|_______________|");*/
                    } else if (diaN >= 22 && diaN <= 31) {
                        
                        textFinal.setText("Geminis.");
                        
                        /*System.out.println("___________________");
                        System.out.println("| Tu eres Geminis |");
                        System.out.println("|_________________|");*/
                    }
                }
                case (6) -> {
                    if (diaN >= 1 && diaN <= 21) {
                        
                        textFinal.setText("Geminis.");
                        
                        /*System.out.println("___________________");
                        System.out.println("| Tu eres Geminis |");
                        System.out.println("|_________________|");*/
                    } else if (diaN >= 22 && diaN <= 30) {
                        
                        textFinal.setText("Cancer.");
                        
                        /*System.out.println("__________________");
                        System.out.println("| Tu eres Cancer |");
                        System.out.println("|________________|");*/
                    } else {
                        
                        textFinal.setText("ERROR.");
                        JOptionPane.showMessageDialog(null, "Eres un Dios naciste un dia que no existe!");
                        
                        /*System.out.println("______________________________________________");
                        System.out.println("| Eres un Dios naciste un dia que no existe! |");
                        System.out.println("|____________________________________________|");*/
                    }
                }
                case (7) -> {
                    if (diaN >= 1 && diaN <= 22) {
                        
                        textFinal.setText("Cancer.");
                        
                        /*System.out.println("__________________");
                        System.out.println("| Tu eres Cancer |");
                        System.out.println("|________________|");*/
                    } else if (diaN >= 23 && diaN <= 31) {
                        
                        textFinal.setText("Leo.");
                        
                        /*System.out.println("_______________");
                        System.out.println("| Tu eres Leo |");
                        System.out.println("|_____________|");*/
                    }
                }
                case (8) -> {
                    if (diaN >= 1 && diaN <= 23) {
                        
                        textFinal.setText("Leo.");
                        
                        /*System.out.println("_______________");
                        System.out.println("| Tu eres Leo |");
                        System.out.println("|_____________|");*/
                    } else if (diaN >= 24 && diaN <= 31) {
                        
                        textFinal.setText("Virgo.");
                        
                        /*System.out.println("_________________");
                        System.out.println("| Tu eres Virgo |");
                        System.out.println("|_______________|");*/
                    }
                }
                case (9) -> {
                    if (diaN >= 1 && diaN <= 23) {
                        
                        textFinal.setText("Virgo.");
                        
                        /*System.out.println("_________________");
                        System.out.println("| Tu eres Virgo |");
                        System.out.println("|_______________|");*/
                    } else if (diaN >= 24 && diaN <= 30) {
                        
                        textFinal.setText("Libra.");
                        
                        /*System.out.println("_________________");
                        System.out.println("| Tu eres Libra |");
                        System.out.println("|_______________|");*/
                    } else {
                        
                        textFinal.setText("ERROR.");
                        JOptionPane.showMessageDialog(null, "Eres un Dios naciste un dia que no existe!");
                        
                        /*System.out.println("______________________________________________");
                        System.out.println("| Eres un Dios naciste un dia que no existe! |");
                        System.out.println("|____________________________________________|");*/
                    }
                }
                case (10) -> {
                    if (diaN >= 1 && diaN <= 23) {
                        
                        textFinal.setText("Libra.");
                        
                        /*System.out.println("_________________");
                        System.out.println("| Tu eres Libra |");
                        System.out.println("|_______________|");*/
                    } else if (diaN >= 24 && diaN <= 31) {
                        
                        textFinal.setText("Escorpio.");
                        
                        /*System.out.println("____________________");
                        System.out.println("| Tu eres Escorpio |");
                        System.out.println("|__________________|");*/
                    }
                }
                case (11) -> {
                    if (diaN >= 1 && diaN <= 22) {
                        
                        textFinal.setText("Escorpio.");
                        
                        /*System.out.println("____________________");
                        System.out.println("| Tu eres Escorpio |");
                        System.out.println("|__________________|");*/
                    } else if (diaN >= 23 && diaN <= 30) {
                        
                        textFinal.setText("Sagitario.");
                        
                        /*System.out.println("_____________________");
                        System.out.println("| Tu eres Sagitario |");
                        System.out.println("|___________________|");*/
                    } else {
                        
                        textFinal.setText("ERROR.");
                        JOptionPane.showMessageDialog(null, "Eres un Dios naciste un dia que no existe!");
                        
                        /*System.out.println("______________________________________________");
                        System.out.println("| Eres un Dios naciste un dia que no existe! |");
                        System.out.println("|____________________________________________|");*/
                    }
                }
                case (12) -> {
                    if (diaN >= 1 && diaN <= 21) {
                        
                        textFinal.setText("Sagitario.");
                        /*System.out.println("_____________________");
                        System.out.println("| Tu eres Sagitario |");
                        System.out.println("|___________________|");*/
                    } else if (diaN >= 22 && diaN <= 31) {
                        
                        textFinal.setText("Capricornio.");

                        /*System.out.println("_______________________");
                        System.out.println("| Tu eres Capricornio |");
                        System.out.println("|_____________________|");*/
                    }
                }
            }
            // Enero
            // Febrero
            // Marzo
            // Abril
            // Mayo
            // Junio
            // Julio
            // Agosto
            // Septiembre
            // Octubre
            // Noviembre
            // Diciembre
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFinalActionPerformed

    private void textMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignoZodiaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignoZodiaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignoZodiaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignoZodiaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignoZodiaco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textDia;
    private javax.swing.JTextField textFinal;
    private javax.swing.JTextField textMes;
    // End of variables declaration//GEN-END:variables
}
